<?php
/**
 * gcwoo functions and definitions.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package gcwoo
 */

if ( ! function_exists( 'gcwoo_setup' ) ) :
/**
 * Sets up theme defaults and registers support for various WordPress features.
 *
 * Note that this function is hooked into the after_setup_theme hook, which
 * runs before the init hook. The init hook is too late for some features, such
 * as indicating support for post thumbnails.
 */
function gcwoo_setup() {
	/*
	 * Make theme available for translation.
	 * Translations can be filed in the /languages/ directory.
	 * If you're building a theme based on gcwoo, use a find and replace
	 * to change 'gcwoo' to the name of your theme in all the template files.
	 */
	load_theme_textdomain( 'gcwoo', get_template_directory() . '/languages' );

	// Add default posts and comments RSS feed links to head.
	add_theme_support( 'automatic-feed-links' );

	/*
	 * Let WordPress manage the document title.
	 * By adding theme support, we declare that this theme does not use a
	 * hard-coded <title> tag in the document head, and expect WordPress to
	 * provide it for us.
	 */
	add_theme_support( 'title-tag' );

	/*
	 * Enable support for Post Thumbnails on posts and pages.
	 *
	 * @link https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/
	 */
	add_theme_support( 'post-thumbnails' );
	
	if ( function_exists( 'add_image_size' ) ) {
		//Blog
		add_image_size( 'gcwoo_post', 953, 536, true );
		add_image_size( 'gcwoo_blog-section', 457, 259, true );
		add_image_size( 'gcwoo_post_square', 457, 457, true );

		//Portfolio
		add_image_size( 'gcwoo_portfolio_square', 953, 953, true );
		add_image_size( 'gcwoo_portfolio_landscape', 953, 476, true );
	}

	// This theme uses wp_nav_menu() in one location.
	register_nav_menus( array(
		'primary' => esc_html__( 'Primary Menu', 'gcwoo' ),
		'front-page' => esc_html__( 'Front Page Menu', 'gcwoo' ),
		'product-page' => esc_html__( 'Product Menu', 'gcwoo' ),
		'social' => esc_html__( 'Social Menu', 'gcwoo' ),
	) );

	/*
	 * Switch default core markup for search form, comment form, and comments
	 * to output valid HTML5.
	 */
	add_theme_support( 'html5', array(
		'search-form',
		'comment-form',
		'comment-list',
		'gallery',
		'caption',
	) );


	// Set up the WordPress core custom background feature.
	add_theme_support( 'custom-background', apply_filters( 'gcwoo_custom_background_args', array(
		'default-color' => 'ffffff',
		'default-image' => '',
	) ) );

	// Styles for TinyMCE
	$font_url = str_replace( ',', '%2C', '//fonts.googleapis.com/css?family=Lato:300,400,700' );
    add_editor_style( array( 'css/editor-style.css', 'css/bootstrap.css', $font_url )  );
	
}
endif; // gcwoo_setup
add_action( 'after_setup_theme', 'gcwoo_setup' );


/**
 * Set the content width in pixels, based on the theme's design and stylesheet.
 *
 * Priority 0 to make it available to lower priority callbacks.
 *
 * @global int $content_width
 */
function gcwoo_content_width() {
	$GLOBALS['content_width'] = apply_filters( 'gcwoo_content_width', 953 );
}
add_action( 'after_setup_theme', 'gcwoo_content_width', 0 );



/**
 * Register widget area.
 *
 * @link https://developer.wordpress.org/themes/functionality/sidebars/#registering-a-sidebar
 */
function gcwoo_widgets_init() {

	require get_template_directory() . '/inc/widget-areas/widget-areas.php';

}
add_action( 'widgets_init', 'gcwoo_widgets_init' );



/**
 * Register widgets.
 *
 * @link https://codex.wordpress.org/Widgets_API
 */
function gcwoo_widgets_register() {

	require get_template_directory() . '/inc/widgets/service.php';
	require get_template_directory() . '/inc/widgets/client.php';
	require get_template_directory() . '/inc/widgets/pricing.php';

}
add_action( 'widgets_init', 'gcwoo_widgets_register' );



/**
 * Enqueue scripts and styles.
 */
function gcwoo_scripts() {

	/**
	 * Enqueue Stylesheets
	 */
	require get_template_directory() . '/inc/scripts/stylesheets.php';

	/**
	 * Enqueue Scripts
	 */
	require get_template_directory() . '/inc/scripts/scripts.php';

}
add_action( 'wp_enqueue_scripts', 'gcwoo_scripts' );



/**
 * Custom CSS generated by the Theme.
 */
require get_template_directory() . '/inc/scripts/styles.php';



/**
 * Admin Styles
 *
 * Enqueue styles to the Admin Panel.
 */
function gcwoo_wp_admin_style() {
        wp_register_style( 'gcwoo_custom_wp_admin_css', get_template_directory_uri() . '/css/admin-styles.css', false, '1.0.0' );
        wp_enqueue_style( 'gcwoo_custom_wp_admin_css' );
}
add_action( 'admin_enqueue_scripts', 'gcwoo_wp_admin_style' );



/**
 * Custom template tags for this theme.
 */
require get_template_directory() . '/inc/template-tags.php';



/**
 * Extras
 *
 * Custom functions that act independently of the theme templates.
 */
require get_template_directory() . '/inc/extras.php';



/**
 * Customizer
 *
 * Customizer additions.
 */
require get_template_directory() . '/inc/customizer.php';



/**
 * Theme Functions
 *
 * Add Theme Functions
 */

	// Bootstrap Walker
	require get_template_directory() . '/inc/theme-functions/wp_bootstrap_navwalker.php';

	// Custom Header
	require get_template_directory() . '/inc/theme-functions/custom-header.php';

	// TGM Plugin Activation
	require get_template_directory() . '/inc/theme-functions/ql_tgm_plugin_activation.php';



/**
 * WooCommerce Hooks
 * 
 * Remove and Declare Hook Functions
 */

	// Unhook WooCommerce Wrappers
	remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10);
	remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10);
	
	// Hook WooCommerce Main Wrapper
	add_action('woocommerce_before_main_content', 'my_theme_wrapper_start', 10);
	add_action('woocommerce_after_main_content', 'my_theme_wrapper_end', 10);
	
	function my_theme_wrapper_start() {
	  echo '<section id="main" class="main" style="margin-top:125px;"><div class="container">';
	}
	
	function my_theme_wrapper_end() {
	  echo '</div></section>';
	}
	
/**
 * WooCommerce Functions
 * 
 * Add Theme Functions
 */	

	//Declare WooCommerce Theme Support
	add_action( 'after_setup_theme', 'woocommerce_support' );
	function woocommerce_support() {
	    add_theme_support( 'woocommerce' );
	}

